- name: playbook for filesystem Creation
  hosts: all
  become: yes
  tasks:
    - include_vars:
        file: filesystemstrippingvar.yaml

    - name: Display contents
      shell: "ls -ll /dev/disk/azure/scsi1/lun{{lun1}} | awk '{print $11}' | cut -d '/' -f 4-"
      register: command_output1
    - name: Display contents
      shell: "ls -ll /dev/disk/azure/scsi1/lun{{lun2}} | awk '{print $11}' | cut -d '/' -f 4-"
      register: command_output2

    - name: Install lvm2 dependency
      package:
        name: lvm2
        state: present    

    - name: Create Physical Volumes
      shell: |
        pvcreate /dev/"{{command_output1.stdout}}" /dev/"{{command_output2.stdout}}"

    - name: Create Volume Group
      shell: |
        vgcreate "{{vg_name}}" /dev/"{{command_output1.stdout}}" /dev/"{{command_output2.stdout}}"

    - name: Create Striped Logical Volume
      shell: |
        lvcreate -i{{volumecount}}  -I {{stsize}} -L {{lvsize}} -n {{lv_name}} {{vg_name}}

    - name: Create directory mountpoint if does not exist
      file:
        path: "{{dir}}"
        state: directory
        mode: '0777'

    - name: format the xfs filesystem
      filesystem:
        fstype: "{{ftype}}"
        dev: /dev/{{vg_name}}/{{lv_name}}

    - name: mount the lv on mountpoint
      mount:
        src: /dev/{{vg_name}}/{{lv_name}}
        fstype: "{{ftype}}"
        state: mounted
        path: "{{ dir }}"
