---
- name: Playbook for patching
  hosts: all
  become: true
  tasks:
    - include_vars:
        file: rhelpatchvar.yaml
    - name: List all packages()
      yum:
        list: updates
        update_cache: true
      register: yumoutput
    - debug: msg="{{ inventory_hostname}} {{ yumoutput.results }}"
    - name: Updating all packages
      yum:
        name: "{{yuminput}}"
        state: latest

