- hosts: all
  become: yes
  tasks:
  - include_vars:
          file: swapvar.yml
  - name: creating new LVM volume group
    lvg: vg={{vgname}} pvs=/dev/disk/azure/scsi1/lun{{lun}} state=present

 # Normally assigned swap size is two times of memory
  - name: creating new LVM logical volume
    lvol: vg={{vgname}} lv={{lvname}} size={{extend_size}}

  - name: Format swap device
    command: mkswap /dev/{{vgname}}/{{lvname}}
    when: ansible_swaptotal_mb < 1

  - name: activate swap device
    command: swapon /dev/{{vgname}}/{{lvname}}
    when: ansible_swaptotal_mb < 1

  - name: Add to fstab
    action: lineinfile dest=/etc/fstab regexp="/dev/{{vgname}}/{{lvname}}" line="/dev/{{vgname}}/{{lvname}} swap swap defaults 0 0" state=present